[[xxHash]]
arch = "aarch64"
git-tree-sha1 = "cd0a4bff892b73c0b131f17944e71e9c6d6d6f92"
os = "macos"

    [[xxHash.download]]
    sha256 = "a466f719dfbf6b359973e5a41bd659cb5f01e7737fa58dafaadfc216aba6aa02"
    url = "https://github.com/JuliaBinaryWrappers/xxHash_jll.jl/releases/download/xxHash-v0.8.1+0/xxHash.v0.8.1.aarch64-apple-darwin.tar.gz"
[[xxHash]]
arch = "aarch64"
git-tree-sha1 = "5c0eba907f926be68bf4b7de08ca127b37bbe098"
libc = "glibc"
os = "linux"

    [[xxHash.download]]
    sha256 = "e77844413188d0d0dd14775a040ea90397132bd37dac637c860a7175218cf954"
    url = "https://github.com/JuliaBinaryWrappers/xxHash_jll.jl/releases/download/xxHash-v0.8.1+0/xxHash.v0.8.1.aarch64-linux-gnu.tar.gz"
[[xxHash]]
arch = "aarch64"
git-tree-sha1 = "ff76089ea36f9b51531793b25a274f4a82dc9552"
libc = "musl"
os = "linux"

    [[xxHash.download]]
    sha256 = "93aecc8ea0aacc5308daf08fa191d6c8837396b55bb0ea0c5fd53d5741fabb40"
    url = "https://github.com/JuliaBinaryWrappers/xxHash_jll.jl/releases/download/xxHash-v0.8.1+0/xxHash.v0.8.1.aarch64-linux-musl.tar.gz"
[[xxHash]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "f4e92a5ba1802c94e808e00a6f6f26d1fbd12d9e"
libc = "glibc"
os = "linux"

    [[xxHash.download]]
    sha256 = "8a180d9310e4f136486713967e43fadc24d9aed7e3872e2a6e14f5065a8df445"
    url = "https://github.com/JuliaBinaryWrappers/xxHash_jll.jl/releases/download/xxHash-v0.8.1+0/xxHash.v0.8.1.armv6l-linux-gnueabihf.tar.gz"
[[xxHash]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "97feaf3875e05b3480c44966d0dd1c2aea4f9b83"
libc = "musl"
os = "linux"

    [[xxHash.download]]
    sha256 = "b4d9b00350c2a28f9c8d70c99fce3368969d380c05075feabf047573d90f0a37"
    url = "https://github.com/JuliaBinaryWrappers/xxHash_jll.jl/releases/download/xxHash-v0.8.1+0/xxHash.v0.8.1.armv6l-linux-musleabihf.tar.gz"
[[xxHash]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "3e79f1600eade6858cdf422366462638d664154f"
libc = "glibc"
os = "linux"

    [[xxHash.download]]
    sha256 = "41f3f8d72ab813128944034c348cdca5aee3de0686da529da4fa403231bdfca4"
    url = "https://github.com/JuliaBinaryWrappers/xxHash_jll.jl/releases/download/xxHash-v0.8.1+0/xxHash.v0.8.1.armv7l-linux-gnueabihf.tar.gz"
[[xxHash]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "4909be1f148557fb4566534dee418ccfb810ab0c"
libc = "musl"
os = "linux"

    [[xxHash.download]]
    sha256 = "1cb3d0a9b9a8a368258631cf608f28342b356bbbd03e44cfef198f2c8d000b35"
    url = "https://github.com/JuliaBinaryWrappers/xxHash_jll.jl/releases/download/xxHash-v0.8.1+0/xxHash.v0.8.1.armv7l-linux-musleabihf.tar.gz"
[[xxHash]]
arch = "i686"
git-tree-sha1 = "b04bac20fe121d0b2718fbb21047241953c21f60"
libc = "glibc"
os = "linux"

    [[xxHash.download]]
    sha256 = "7ace5938a94289b80bdda1302631ecdf210653fc8a96a740dbe60e63e9d55db9"
    url = "https://github.com/JuliaBinaryWrappers/xxHash_jll.jl/releases/download/xxHash-v0.8.1+0/xxHash.v0.8.1.i686-linux-gnu.tar.gz"
[[xxHash]]
arch = "i686"
git-tree-sha1 = "2d91d4d8f02be38695a118ae6e11fb1229fdecb7"
libc = "musl"
os = "linux"

    [[xxHash.download]]
    sha256 = "b5e3452eea39eaaf756d83401baea843f6156f8736c31a47095702e61ecdd533"
    url = "https://github.com/JuliaBinaryWrappers/xxHash_jll.jl/releases/download/xxHash-v0.8.1+0/xxHash.v0.8.1.i686-linux-musl.tar.gz"
[[xxHash]]
arch = "i686"
git-tree-sha1 = "920ba89f29c08a9dfab13b6047c742432ca9c68f"
os = "windows"

    [[xxHash.download]]
    sha256 = "4fb07c2fb5a51d2e85a8e75837a44fa6a069a1d811f455beca5ca8978a87994c"
    url = "https://github.com/JuliaBinaryWrappers/xxHash_jll.jl/releases/download/xxHash-v0.8.1+0/xxHash.v0.8.1.i686-w64-mingw32.tar.gz"
[[xxHash]]
arch = "powerpc64le"
git-tree-sha1 = "a1c1b8a1de2ae4c1df6ac4ce1f345a262506fb70"
libc = "glibc"
os = "linux"

    [[xxHash.download]]
    sha256 = "1cfa5b91c47f4f385b437e1f9889e1171007624fdc56dbc01296bb88198eb26f"
    url = "https://github.com/JuliaBinaryWrappers/xxHash_jll.jl/releases/download/xxHash-v0.8.1+0/xxHash.v0.8.1.powerpc64le-linux-gnu.tar.gz"
[[xxHash]]
arch = "x86_64"
git-tree-sha1 = "2dff91d0b70f162d489dda463ab7c54a121bc26d"
os = "macos"

    [[xxHash.download]]
    sha256 = "eb16ef97bbded8b6bafb01d00586e934aa332787f9b90262f9b24d1e5b732ca0"
    url = "https://github.com/JuliaBinaryWrappers/xxHash_jll.jl/releases/download/xxHash-v0.8.1+0/xxHash.v0.8.1.x86_64-apple-darwin.tar.gz"
[[xxHash]]
arch = "x86_64"
git-tree-sha1 = "444dea06bb5807dab9f97eca9243804a9a875735"
libc = "glibc"
os = "linux"

    [[xxHash.download]]
    sha256 = "c7ef9a9549c7a450bed068aa04e3875acdd2a1ecfdb98f24f0e25eae1f13c996"
    url = "https://github.com/JuliaBinaryWrappers/xxHash_jll.jl/releases/download/xxHash-v0.8.1+0/xxHash.v0.8.1.x86_64-linux-gnu.tar.gz"
[[xxHash]]
arch = "x86_64"
git-tree-sha1 = "ca7a51b8060cf600dcbfdf081b24aee0a0a8eebf"
libc = "musl"
os = "linux"

    [[xxHash.download]]
    sha256 = "61b29ee3665d0ca5e570a3f2597503d30885c61f7d268d90f6831d99f5f15379"
    url = "https://github.com/JuliaBinaryWrappers/xxHash_jll.jl/releases/download/xxHash-v0.8.1+0/xxHash.v0.8.1.x86_64-linux-musl.tar.gz"
[[xxHash]]
arch = "x86_64"
git-tree-sha1 = "da60132ce8a8ce32b7a0a8cc48e604ef274575e4"
os = "freebsd"

    [[xxHash.download]]
    sha256 = "c68d22f791a25bd7e8ee64bff0df0ceda4cb1e6a1f85b741562ef8c171c65489"
    url = "https://github.com/JuliaBinaryWrappers/xxHash_jll.jl/releases/download/xxHash-v0.8.1+0/xxHash.v0.8.1.x86_64-unknown-freebsd.tar.gz"
[[xxHash]]
arch = "x86_64"
git-tree-sha1 = "9fca5727a6cc71ebe7973c1f93badb85e8c85485"
os = "windows"

    [[xxHash.download]]
    sha256 = "b5ba4a76332e99d0392607e7eb0a5ce9974575a6cbf9599e2f66ebdd3b0bedbb"
    url = "https://github.com/JuliaBinaryWrappers/xxHash_jll.jl/releases/download/xxHash-v0.8.1+0/xxHash.v0.8.1.x86_64-w64-mingw32.tar.gz"
