[[xxHash]]
arch = "aarch64"
git-tree-sha1 = "7728792efbd4af96da3e92968c2ba7f2beeca2c9"
os = "macos"

    [[xxHash.download]]
    sha256 = "3242b16b62f64b3c1306858b97e0686b499bfbd6411a5559053bd4c0119e2a81"
    url = "https://github.com/JuliaBinaryWrappers/xxHash_jll.jl/releases/download/xxHash-v0.8.1+1/xxHash.v0.8.1.aarch64-apple-darwin.tar.gz"
[[xxHash]]
arch = "aarch64"
git-tree-sha1 = "4ae658b47703596ddb69c5a80dd1cf01e4064a24"
libc = "glibc"
os = "linux"

    [[xxHash.download]]
    sha256 = "fb325a150694c675cbd10800bcc7a953b6f510bac03dd6a3c9c412c3abe52578"
    url = "https://github.com/JuliaBinaryWrappers/xxHash_jll.jl/releases/download/xxHash-v0.8.1+1/xxHash.v0.8.1.aarch64-linux-gnu.tar.gz"
[[xxHash]]
arch = "aarch64"
git-tree-sha1 = "f60b9e4f5a9898a2c053c979637237f6486b139c"
libc = "musl"
os = "linux"

    [[xxHash.download]]
    sha256 = "a7fef6653101134cedd883658816d792e3e889ffc82bdafe5387db3f05b90d9e"
    url = "https://github.com/JuliaBinaryWrappers/xxHash_jll.jl/releases/download/xxHash-v0.8.1+1/xxHash.v0.8.1.aarch64-linux-musl.tar.gz"
[[xxHash]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "619734e8c9428c8bcf56634d1d55aa3a57f7a566"
libc = "glibc"
os = "linux"

    [[xxHash.download]]
    sha256 = "24cceaac6b3341ca89611318b4250f8830e364b7361286e24bbe6d05db6c77fa"
    url = "https://github.com/JuliaBinaryWrappers/xxHash_jll.jl/releases/download/xxHash-v0.8.1+1/xxHash.v0.8.1.armv6l-linux-gnueabihf.tar.gz"
[[xxHash]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a37920dd6de354509a556984b2a4dd02fbbc58d6"
libc = "musl"
os = "linux"

    [[xxHash.download]]
    sha256 = "ef7b3a00ef46b822bb9049fc394cb8bd3bc39a393446ecc7ac2bf7cb37761d3d"
    url = "https://github.com/JuliaBinaryWrappers/xxHash_jll.jl/releases/download/xxHash-v0.8.1+1/xxHash.v0.8.1.armv6l-linux-musleabihf.tar.gz"
[[xxHash]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a2a5078abd9b51b6d8077ca12e41d1099c8f1938"
libc = "glibc"
os = "linux"

    [[xxHash.download]]
    sha256 = "1a273ab10a942d1277bf46bab2d44aaf9955b1f552ee771e628598271aa62680"
    url = "https://github.com/JuliaBinaryWrappers/xxHash_jll.jl/releases/download/xxHash-v0.8.1+1/xxHash.v0.8.1.armv7l-linux-gnueabihf.tar.gz"
[[xxHash]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "290edace81f56dc8357e961184d6901b58b24038"
libc = "musl"
os = "linux"

    [[xxHash.download]]
    sha256 = "f6ddc295c92dcb86b150d3044c8fbb2e4c48ae2fecc857b9af449b4507878208"
    url = "https://github.com/JuliaBinaryWrappers/xxHash_jll.jl/releases/download/xxHash-v0.8.1+1/xxHash.v0.8.1.armv7l-linux-musleabihf.tar.gz"
[[xxHash]]
arch = "i686"
git-tree-sha1 = "7486ac68ce1cf5f69a651985c35e40d28bcebf2a"
libc = "glibc"
os = "linux"

    [[xxHash.download]]
    sha256 = "cb2ae225fcf67cd710efb171239dc29c6129fd7625cf111443c55bc818c0410f"
    url = "https://github.com/JuliaBinaryWrappers/xxHash_jll.jl/releases/download/xxHash-v0.8.1+1/xxHash.v0.8.1.i686-linux-gnu.tar.gz"
[[xxHash]]
arch = "i686"
git-tree-sha1 = "6d16b2b5759e7facbd562a1df2c1947ee4d8b208"
libc = "musl"
os = "linux"

    [[xxHash.download]]
    sha256 = "09b10c9a1d8affa9fe0e91d447b1733cc3bd51ef5c83db8506011f2f4f7654d3"
    url = "https://github.com/JuliaBinaryWrappers/xxHash_jll.jl/releases/download/xxHash-v0.8.1+1/xxHash.v0.8.1.i686-linux-musl.tar.gz"
[[xxHash]]
arch = "i686"
git-tree-sha1 = "281053e23c2862c8ed5cb921e6b7fa0f6d4953b2"
os = "windows"

    [[xxHash.download]]
    sha256 = "9b432d52ca3fb039521a47a26a77d459f150a448f5efd6aad0a683835fd983dc"
    url = "https://github.com/JuliaBinaryWrappers/xxHash_jll.jl/releases/download/xxHash-v0.8.1+1/xxHash.v0.8.1.i686-w64-mingw32.tar.gz"
[[xxHash]]
arch = "powerpc64le"
git-tree-sha1 = "dd378932f26d0c94f21a44a60f73d79c40c3f57b"
libc = "glibc"
os = "linux"

    [[xxHash.download]]
    sha256 = "0609bb2b7ea594c18a38c4f6a4a92ccfb2749f251db5831bf3b8ee1252964c52"
    url = "https://github.com/JuliaBinaryWrappers/xxHash_jll.jl/releases/download/xxHash-v0.8.1+1/xxHash.v0.8.1.powerpc64le-linux-gnu.tar.gz"
[[xxHash]]
arch = "x86_64"
git-tree-sha1 = "9456fd1c084d3924a2fb320fd252e1aca00abc84"
os = "macos"

    [[xxHash.download]]
    sha256 = "7988cb060fa889eb11732d08afb8ee08dc7e3e3e07382db5c907d805837bff4f"
    url = "https://github.com/JuliaBinaryWrappers/xxHash_jll.jl/releases/download/xxHash-v0.8.1+1/xxHash.v0.8.1.x86_64-apple-darwin.tar.gz"
[[xxHash]]
arch = "x86_64"
git-tree-sha1 = "13ab51aa94fca17cd1fbd3b9ce14f303e481893e"
libc = "glibc"
os = "linux"

    [[xxHash.download]]
    sha256 = "9b1b7babeb6a54c1873178cb75fdfb72cd09ddfc860c89f1f9de2643b89c0a08"
    url = "https://github.com/JuliaBinaryWrappers/xxHash_jll.jl/releases/download/xxHash-v0.8.1+1/xxHash.v0.8.1.x86_64-linux-gnu.tar.gz"
[[xxHash]]
arch = "x86_64"
git-tree-sha1 = "b28ef2369419be702ac501d47762fe2c88cb071f"
libc = "musl"
os = "linux"

    [[xxHash.download]]
    sha256 = "7aaddbe9cf8ecca472342fda043aed7110b527d1569d8d880bbb4ef1c8a89d7b"
    url = "https://github.com/JuliaBinaryWrappers/xxHash_jll.jl/releases/download/xxHash-v0.8.1+1/xxHash.v0.8.1.x86_64-linux-musl.tar.gz"
[[xxHash]]
arch = "x86_64"
git-tree-sha1 = "b2fec712902c75e91fb19fa52af8b10d5d08cfd6"
os = "freebsd"

    [[xxHash.download]]
    sha256 = "5dd182070fce3f4d43bad5f73a2cdfe3a3e81532e358e51f61761853cea2cdd7"
    url = "https://github.com/JuliaBinaryWrappers/xxHash_jll.jl/releases/download/xxHash-v0.8.1+1/xxHash.v0.8.1.x86_64-unknown-freebsd.tar.gz"
[[xxHash]]
arch = "x86_64"
git-tree-sha1 = "27074ef5475dcaf2b44c4a36cc17a4de3a11fb95"
os = "windows"

    [[xxHash.download]]
    sha256 = "6ef71c3fc69c29d591ef4d8d092188b48b2a92063abfb300a604feae5dd6fba0"
    url = "https://github.com/JuliaBinaryWrappers/xxHash_jll.jl/releases/download/xxHash-v0.8.1+1/xxHash.v0.8.1.x86_64-w64-mingw32.tar.gz"
