[[xxHash]]
arch = "aarch64"
git-tree-sha1 = "981800f8afe1e5cc2e8c7b07f20284bfe087dfbc"
os = "macos"

    [[xxHash.download]]
    sha256 = "7b0caabaa160640b63af06b478c3c8ca03201c11e5668b1f7c39cae4dadff477"
    url = "https://github.com/JuliaBinaryWrappers/xxHash_jll.jl/releases/download/xxHash-v0.8.3+0/xxHash.v0.8.3.aarch64-apple-darwin.tar.gz"
[[xxHash]]
arch = "aarch64"
git-tree-sha1 = "0933be76aca53b8d0a374d3b5c2d31df95637546"
libc = "glibc"
os = "linux"

    [[xxHash.download]]
    sha256 = "abfdbc290e5e3ceb224ae3911e80e14a6679e22b4f412d331def0ed5a47be5e0"
    url = "https://github.com/JuliaBinaryWrappers/xxHash_jll.jl/releases/download/xxHash-v0.8.3+0/xxHash.v0.8.3.aarch64-linux-gnu.tar.gz"
[[xxHash]]
arch = "aarch64"
git-tree-sha1 = "2513d0e865575e1adc68e53645fb58379fad68d0"
libc = "musl"
os = "linux"

    [[xxHash.download]]
    sha256 = "717a23063638fbde9318c8dc7b7ff815de6e1695e13647687c90b4f4c9a47781"
    url = "https://github.com/JuliaBinaryWrappers/xxHash_jll.jl/releases/download/xxHash-v0.8.3+0/xxHash.v0.8.3.aarch64-linux-musl.tar.gz"
[[xxHash]]
arch = "aarch64"
git-tree-sha1 = "444f79cadbbacd0d23521d201cea3efd47550e27"
os = "freebsd"

    [[xxHash.download]]
    sha256 = "ac3c49032123023b394bbb9eeeaa154a25734cf462ce295ac62dfd0c60d99b5f"
    url = "https://github.com/JuliaBinaryWrappers/xxHash_jll.jl/releases/download/xxHash-v0.8.3+0/xxHash.v0.8.3.aarch64-unknown-freebsd.tar.gz"
[[xxHash]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "237c65aaba0d1718483e7d00c015383a58457e9c"
libc = "glibc"
os = "linux"

    [[xxHash.download]]
    sha256 = "f94134b603faa6f6f79b160f2773ce55c5d3ffc6a037fa712fea60ae8dd9bf36"
    url = "https://github.com/JuliaBinaryWrappers/xxHash_jll.jl/releases/download/xxHash-v0.8.3+0/xxHash.v0.8.3.armv6l-linux-gnueabihf.tar.gz"
[[xxHash]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a5f1e359d5f7122c838471326d7fecf6aa6572ef"
libc = "musl"
os = "linux"

    [[xxHash.download]]
    sha256 = "06f4d7d79aa24b39aa6044acd798e28bd303c651222f360f947520666fb13abb"
    url = "https://github.com/JuliaBinaryWrappers/xxHash_jll.jl/releases/download/xxHash-v0.8.3+0/xxHash.v0.8.3.armv6l-linux-musleabihf.tar.gz"
[[xxHash]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "6750e78a5b69f296d763071c66ba34fe1ed51dd7"
libc = "glibc"
os = "linux"

    [[xxHash.download]]
    sha256 = "4a4730acd24bc6c5d55c7b6f98e633a4dd781c6eda10a39ac6e812740b0f73b7"
    url = "https://github.com/JuliaBinaryWrappers/xxHash_jll.jl/releases/download/xxHash-v0.8.3+0/xxHash.v0.8.3.armv7l-linux-gnueabihf.tar.gz"
[[xxHash]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "74c41c96dc35bc030dd17f5f75b4a3d71326cd84"
libc = "musl"
os = "linux"

    [[xxHash.download]]
    sha256 = "7ea6ebe8e97fbca8f7cc0e0603ba1bb08208b9d3415f3aa3469a4b9a826dad78"
    url = "https://github.com/JuliaBinaryWrappers/xxHash_jll.jl/releases/download/xxHash-v0.8.3+0/xxHash.v0.8.3.armv7l-linux-musleabihf.tar.gz"
[[xxHash]]
arch = "i686"
git-tree-sha1 = "deb1c3bf25d1b92f88e2b567ceb1bdfc55e71c0e"
libc = "glibc"
os = "linux"

    [[xxHash.download]]
    sha256 = "cbc079dc4a95d2fcaacff109c5d2518296fa2b4f0d66947ebe9424d75114ccd2"
    url = "https://github.com/JuliaBinaryWrappers/xxHash_jll.jl/releases/download/xxHash-v0.8.3+0/xxHash.v0.8.3.i686-linux-gnu.tar.gz"
[[xxHash]]
arch = "i686"
git-tree-sha1 = "985ec343a58c49b558e8975d7e9fef1d37514724"
libc = "musl"
os = "linux"

    [[xxHash.download]]
    sha256 = "acb1b7f7cc2004fb75d0de2887f6ab0af186c4d47d2e79ec5a6d0a4b7af8d5d3"
    url = "https://github.com/JuliaBinaryWrappers/xxHash_jll.jl/releases/download/xxHash-v0.8.3+0/xxHash.v0.8.3.i686-linux-musl.tar.gz"
[[xxHash]]
arch = "i686"
git-tree-sha1 = "b04fcf94f4afc0a33c7263ba81fa655a1d2a26bb"
os = "windows"

    [[xxHash.download]]
    sha256 = "96d3a6747f17622ccf01af4a451a10f6f053f35167a3219dacd51e0c82fe960b"
    url = "https://github.com/JuliaBinaryWrappers/xxHash_jll.jl/releases/download/xxHash-v0.8.3+0/xxHash.v0.8.3.i686-w64-mingw32.tar.gz"
[[xxHash]]
arch = "powerpc64le"
git-tree-sha1 = "54afa14185614e1a6276e8350a0a4dbfc44c1e32"
libc = "glibc"
os = "linux"

    [[xxHash.download]]
    sha256 = "abe1d5e53b4f750fcaa61d5f9f3d90a89a0af9868e4ec107f127daf244097f53"
    url = "https://github.com/JuliaBinaryWrappers/xxHash_jll.jl/releases/download/xxHash-v0.8.3+0/xxHash.v0.8.3.powerpc64le-linux-gnu.tar.gz"
[[xxHash]]
arch = "riscv64"
git-tree-sha1 = "e745d9cfbc1556630e4bc08761d9781e213591cb"
libc = "glibc"
os = "linux"

    [[xxHash.download]]
    sha256 = "8b5aa89b451be59c312dad5f19e531177bffb71e073e56d81ce1b6efa391972a"
    url = "https://github.com/JuliaBinaryWrappers/xxHash_jll.jl/releases/download/xxHash-v0.8.3+0/xxHash.v0.8.3.riscv64-linux-gnu.tar.gz"
[[xxHash]]
arch = "x86_64"
git-tree-sha1 = "168dd713277e9840563453d00196c5d1d8bc9171"
os = "macos"

    [[xxHash.download]]
    sha256 = "70709d76a5ee49043204a395264e141790e63dd6d5442b7f01488f56a3c254a4"
    url = "https://github.com/JuliaBinaryWrappers/xxHash_jll.jl/releases/download/xxHash-v0.8.3+0/xxHash.v0.8.3.x86_64-apple-darwin.tar.gz"
[[xxHash]]
arch = "x86_64"
git-tree-sha1 = "1ca5aff5effe7c3a031f61fd66839ca248c3b555"
libc = "glibc"
os = "linux"

    [[xxHash.download]]
    sha256 = "ce52cb06b9657bd4d9ea6ef995d953a3dd45f89b4fb3eb9ef4f30e2ebc024087"
    url = "https://github.com/JuliaBinaryWrappers/xxHash_jll.jl/releases/download/xxHash-v0.8.3+0/xxHash.v0.8.3.x86_64-linux-gnu.tar.gz"
[[xxHash]]
arch = "x86_64"
git-tree-sha1 = "dbb1d38105af3d57c813d3f6edee03ab85df2f80"
libc = "musl"
os = "linux"

    [[xxHash.download]]
    sha256 = "e68ee8ca966adcd83ac576eef1b000f04d42bbff9923358977b385e0902f3bc6"
    url = "https://github.com/JuliaBinaryWrappers/xxHash_jll.jl/releases/download/xxHash-v0.8.3+0/xxHash.v0.8.3.x86_64-linux-musl.tar.gz"
[[xxHash]]
arch = "x86_64"
git-tree-sha1 = "e7146caaf9547a93464c9cbdd539a134b46a0141"
os = "freebsd"

    [[xxHash.download]]
    sha256 = "a3464d7d6c0207bac612b74e9e763835b199d0942c72d4fcafbaae50edabe728"
    url = "https://github.com/JuliaBinaryWrappers/xxHash_jll.jl/releases/download/xxHash-v0.8.3+0/xxHash.v0.8.3.x86_64-unknown-freebsd.tar.gz"
[[xxHash]]
arch = "x86_64"
git-tree-sha1 = "9977f8e8bfc885df831b696d0b304b1db93293ba"
os = "windows"

    [[xxHash.download]]
    sha256 = "b59772ab8f44e17ef3430c25c244b483fa7d9dd8ff00bbd975ab9e57f7b3487d"
    url = "https://github.com/JuliaBinaryWrappers/xxHash_jll.jl/releases/download/xxHash-v0.8.3+0/xxHash.v0.8.3.x86_64-w64-mingw32.tar.gz"
