[[xxHash]]
arch = "aarch64"
git-tree-sha1 = "24801865dac9a9ae4176071d055a806365253d4d"
libc = "glibc"
os = "linux"

    [[xxHash.download]]
    sha256 = "ced15083276c89a90c535990bf06bf4d032d8f60865735d7d799b9a1423311e6"
    url = "https://github.com/JuliaBinaryWrappers/xxHash_jll.jl/releases/download/xxHash-v0.7.4+0/xxHash.v0.7.4.aarch64-linux-gnu.tar.gz"
[[xxHash]]
arch = "aarch64"
git-tree-sha1 = "05e2f3ab68c14c29e9d3566c470807d39addcf42"
libc = "musl"
os = "linux"

    [[xxHash.download]]
    sha256 = "0fd311b5da87dcbe7e7c47c49a3ea98ae5686570253b8f18c3721e90f7bd70de"
    url = "https://github.com/JuliaBinaryWrappers/xxHash_jll.jl/releases/download/xxHash-v0.7.4+0/xxHash.v0.7.4.aarch64-linux-musl.tar.gz"
[[xxHash]]
arch = "armv7l"
git-tree-sha1 = "14236abaa0e6f20225b0c5ce9df21ddfe011a1c7"
libc = "glibc"
os = "linux"

    [[xxHash.download]]
    sha256 = "cb5566d91dda2538ae43fd01f6dd9d4a49aa74a9127efa3e413b22a97b16f0aa"
    url = "https://github.com/JuliaBinaryWrappers/xxHash_jll.jl/releases/download/xxHash-v0.7.4+0/xxHash.v0.7.4.armv7l-linux-gnueabihf.tar.gz"
[[xxHash]]
arch = "armv7l"
git-tree-sha1 = "bcdf413c7d66d05872f79f3aa93408e8b8ba7fe6"
libc = "musl"
os = "linux"

    [[xxHash.download]]
    sha256 = "0348e56532232af4fae4ee29cbd43f2b20635c00a176907e4fb225af1815e4bd"
    url = "https://github.com/JuliaBinaryWrappers/xxHash_jll.jl/releases/download/xxHash-v0.7.4+0/xxHash.v0.7.4.armv7l-linux-musleabihf.tar.gz"
[[xxHash]]
arch = "i686"
git-tree-sha1 = "7dde7bce0aa09bd258798438cd1cfafe62e53024"
libc = "glibc"
os = "linux"

    [[xxHash.download]]
    sha256 = "d99e703ce4dd42bd709d6e69d28acf59f5b66ca88b264b4f520926ceb80fff69"
    url = "https://github.com/JuliaBinaryWrappers/xxHash_jll.jl/releases/download/xxHash-v0.7.4+0/xxHash.v0.7.4.i686-linux-gnu.tar.gz"
[[xxHash]]
arch = "i686"
git-tree-sha1 = "82407f30ddf81154b8567cb40b30da832ccee813"
libc = "musl"
os = "linux"

    [[xxHash.download]]
    sha256 = "243abcddac48777e144a52e0bfffc3f282925dd6bd19faad0f6676b6c12f56e1"
    url = "https://github.com/JuliaBinaryWrappers/xxHash_jll.jl/releases/download/xxHash-v0.7.4+0/xxHash.v0.7.4.i686-linux-musl.tar.gz"
[[xxHash]]
arch = "i686"
git-tree-sha1 = "2f5b7f2b2aa2440549e309a080b235aa2cad1d8a"
os = "windows"

    [[xxHash.download]]
    sha256 = "f9c41828be0f047614d8e6b10ac145070f167514588bc6c0112ddc89151ddbc6"
    url = "https://github.com/JuliaBinaryWrappers/xxHash_jll.jl/releases/download/xxHash-v0.7.4+0/xxHash.v0.7.4.i686-w64-mingw32.tar.gz"
[[xxHash]]
arch = "powerpc64le"
git-tree-sha1 = "999f15596eb2b534b2d2131e33f3ec6a683568a8"
libc = "glibc"
os = "linux"

    [[xxHash.download]]
    sha256 = "84f386ee330a841b7f7cb6dd7ee1a3aa2c0a26fa1ce2e14723b04952b60e6b7f"
    url = "https://github.com/JuliaBinaryWrappers/xxHash_jll.jl/releases/download/xxHash-v0.7.4+0/xxHash.v0.7.4.powerpc64le-linux-gnu.tar.gz"
[[xxHash]]
arch = "x86_64"
git-tree-sha1 = "a620076f7dd70915c0aac25edf25462fa2225d2b"
os = "macos"

    [[xxHash.download]]
    sha256 = "51ace8e326643c3f6f436609f0d5fe0edfe62a5670ef7a8408881e9e8d39f5dc"
    url = "https://github.com/JuliaBinaryWrappers/xxHash_jll.jl/releases/download/xxHash-v0.7.4+0/xxHash.v0.7.4.x86_64-apple-darwin14.tar.gz"
[[xxHash]]
arch = "x86_64"
git-tree-sha1 = "4e33404e8fb351fe9365b015acb44fb53e151029"
libc = "glibc"
os = "linux"

    [[xxHash.download]]
    sha256 = "d63716676bd9e24eb572ddda689311e32f06aae69aa82d8ed78186e36add3cfb"
    url = "https://github.com/JuliaBinaryWrappers/xxHash_jll.jl/releases/download/xxHash-v0.7.4+0/xxHash.v0.7.4.x86_64-linux-gnu.tar.gz"
[[xxHash]]
arch = "x86_64"
git-tree-sha1 = "0e194f84ca5df14733645b5b65d854770e490d8e"
libc = "musl"
os = "linux"

    [[xxHash.download]]
    sha256 = "65c5f86ef01653d0417c48410655265436506780a76aec5473ebe945f3083b47"
    url = "https://github.com/JuliaBinaryWrappers/xxHash_jll.jl/releases/download/xxHash-v0.7.4+0/xxHash.v0.7.4.x86_64-linux-musl.tar.gz"
[[xxHash]]
arch = "x86_64"
git-tree-sha1 = "19ee10cee7b73948e265ccc636ef353627a57fa0"
os = "freebsd"

    [[xxHash.download]]
    sha256 = "899ec48f71a9ab14851e1677be1df2d43bcc3e1b25e532e6347eec0ea3740f41"
    url = "https://github.com/JuliaBinaryWrappers/xxHash_jll.jl/releases/download/xxHash-v0.7.4+0/xxHash.v0.7.4.x86_64-unknown-freebsd11.1.tar.gz"
[[xxHash]]
arch = "x86_64"
git-tree-sha1 = "e890b13d24c0de498baa0f44cb102c67c9f8abbc"
os = "windows"

    [[xxHash.download]]
    sha256 = "994c6dafd1608cc0202a621965e4c0c88bb6563ffb95a750d7a6b270d945c706"
    url = "https://github.com/JuliaBinaryWrappers/xxHash_jll.jl/releases/download/xxHash-v0.7.4+0/xxHash.v0.7.4.x86_64-w64-mingw32.tar.gz"
